---

- name: Create instance
  os_server:
    cloud: "{{ cloud_name }}"
    name: "{{ item.instance_name }}"
    image: "{{ item.instance_image }}"
    meta: "group={{ item.instance_group }},deployment_name={{ item.instance_deployment }}"
    flavor: "{{ item.instance_flavor }}"
    security_groups: "{{ item.instance_security_group }}"
    key_name: "{{ item.instance_keypair }}"
    nics:
      - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  with_items: "{{ instance_info }}"

- name: Add floating IP
  os_floating_ip:
    cloud: "{{ cloud_name }}"
    state: present
    reuse: yes
    server: "{{ item.instance_name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: floatingip
  with_items: "{{ instance_info }}"

- name: debug
  debug: var=floatingip

- name: Wait for instances to be available
  wait_for:
      host: "{{ item.floating_ip.floating_ip_address }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{ floatingip.results }}"
