---

- name: Create flavors
  os_nova_flavor:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
  with_items: "{{ flavor_info }}"
